### ISSUE TITLE
cannot connect to s3 storage

### ISSUE THREAD

**Issue by honza801** [SZTAKI-LPDS/data-avenue#9]
hi,

we cannot connect to minio via s3. docker-compose logs ends with:

```
dataavenue-service     | [05/03/21 14:13:50] INFO  Directories: GET: s3://our.minio.server/minio/test/, key: dataavenue-key, from: 172.18.0.4 (http-apr-8080-exec-3)
dataavenue-service     | [05/03/21 14:13:50] DEBUG ClientAuthentication: TICKET authentication. Client id: dataavenue-key (http-apr-8080-exec-3)
dataavenue-service     | [05/03/21 14:13:50] ERROR Directories: null (http-apr-8080-exec-3)
dataavenue-service     | java.lang.NullPointerException: null
dataavenue-service     | 	at hu.sztaki.lpds.dataavenue.adaptors.s3.S3URIImpl.getPort(S3URIImpl.java:78) ~[data-avenue.adaptor.s3-1.0.0.jar:na]
dataavenue-service     | 	at hu.sztaki.lpds.dataavenue.adaptors.s3.S3Clients.add(S3Clients.java:44) ~[data-avenue.adaptor.s3-1.0.0.jar:na]
dataavenue-service     | 	at hu.sztaki.lpds.dataavenue.adaptors.s3.S3Clients.withClient(S3Clients.java:39) ~[data-avenue.adaptor.s3-1.0.0.jar:na]
dataavenue-service     | 	at hu.sztaki.lpds.dataavenue.adaptors.s3.S3Adaptor.getAmazonS3Client(S3Adaptor.java:150) ~[data-avenue.adaptor.s3-1.0.0.jar:na]
dataavenue-service     | 	at hu.sztaki.lpds.dataavenue.adaptors.s3.S3Adaptor.list(S3Adaptor.java:380) ~[data-avenue.adaptor.s3-1.0.0.jar:na]
dataavenue-service     | 	at hu.sztaki.lpds.dataavenue.core.rest.Directories.list(Directories.java:77) ~[data-avenue.core.service-1.0.0.jar:na]
dataavenue-service     | 	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[na:na]
dataavenue-service     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
dataavenue-service     | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
dataavenue-service     | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110) [jersey-server-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401) [jersey-container-servlet-core-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [jersey-container-servlet-core-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [jersey-container-servlet-core-2.17.jar:na]
dataavenue-service     | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222) [jersey-container-servlet-core-2.17.jar:na]
dataavenue-service     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) [catalina.jar:7.0.108]
dataavenue-service     | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201) [tomcat-coyote.jar:7.0.108]
dataavenue-service     | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654) [tomcat-coyote.jar:7.0.108]
dataavenue-service     | 	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2468) [tomcat-coyote.jar:7.0.108]
dataavenue-service     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
dataavenue-service     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
dataavenue-service     | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.108]
dataavenue-service     | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
```

sftp/http works just fine.

do you have any hints? 

thanks,
jan

**Comment by ahajnal** [comment]
With MinIO the trick is to map its port (9000) to 80 on the host (-p 80:9000, if you start MinIO with docker), and the Data Avenue URI must explicitly specify port number 80, like: s3://our.minio.server**:80**/minio/test/.

I assumed that you didn't use https/certs in minio config. If you don't specify port, Data Avenue assumes default 443 in the case of s3; any port other than 80 will also try to use HTTPS.

NPE at missing port is not very nice; I thought I have fixed it already but apparently not. Thanks for the comment.

bests, akos

**Comment by honza801** [comment]
hi,

we do use https. in the browser https://our.minio.server/minio/test/

for s4cmd fe.

s4cmd --config=.s3cfg --endpoint-url=https://our.minio.server ls s3://test/

do we have to ale configure port 443 in data-avenue? we've tried these urls, neither works

s3://our.minio.server/test
s3://our.minio.server/minio/test

thanks
jan

**Comment by ahajnal** [comment]
Then, use URI: s3://our.minio.server:443/test.
Self-signed certs might not work.
(There is a NPE in the code on missing port number, should go to 443 by default, anyway, I'll fix it.)
bests, akos

**Comment by honza801** [comment]
nice, things got working after appending the port number.

btw. we do not use self signed certificates, but certificates issued by letsencrypt.

thanks
jan

**Comment by ahajnal** [comment]
Develop merged to master.
(Branch develop had the fix to this issue: https://github.com/SZTAKI-LPDS/data-avenue/commit/0d17e970fcd7b72b85cdaab5745195668da5997d)
